# Generated by Django 5.2 on 2025-05-12 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero_casa', models.IntegerField()),
                ('observacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcomodacaoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_url', models.CharField(max_length=255)),
                ('ordem', models.IntegerField(default=1)),
                ('acomodacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acomodacao')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('statusReserva', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], max_length=10)),
                ('acomodacao', models.ForeignKey(db_column='id_acomodacao', on_delete=django.db.models.deletion.CASCADE, to='app.acomodacao')),
            ],
        ),
        migrations.CreateModel(
            name='LogReserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('alteracao', 'Alteração'), ('cancelamento', 'Cancelamento')], max_length=12)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='app.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.CreateModel(
            name='LogUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('alteracao', 'Alteração')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comentario', models.TextField()),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('acomodacao', models.ForeignKey(db_column='id_acomodacao', on_delete=django.db.models.deletion.CASCADE, to='app.acomodacao')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
