# Generated by Django 5.2 on 2025-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_endereco_acomodacaoimagem_reserva_logreserva_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
