# Generated by Django 5.2 on 2025-05-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
    ]
