# Generated by Django 5.2 on 2025-05-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usuario_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acomodacaoimagem',
            old_name='acomodacao_id',
            new_name='acomodacao',
        ),
    ]
