# Generated by Django 5.2 on 2025-05-15 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_acomodacao_id_acomodacaoimagem_acomodacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaousuario',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
