# Generated by Django 5.2 on 2025-05-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_avaliacaousuario_id_alter_logreserva_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='statusReserva',
            new_name='status_reserva',
        ),
    ]
