# Generated by Django 5.2 on 2025-05-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_statusreserva_reserva_status_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status_reserva',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=10),
        ),
    ]
