# Generated by Django 5.2 on 2025-05-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_reserva_status_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('F', 'f'), ('M', 'm')], default='F', max_length=1),
        ),
    ]
