# Generated by Django 5.2 on 2025-05-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('Feminino', 'f'), ('Masculino', 'm')], default='Feminino', max_length=9),
        ),
    ]
