# Generated by Django 5.2 on 2025-05-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logreserva',
            name='acao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('alteracao', 'Alteração'), ('cancelamento', 'Cancelamento')], default='criacao', max_length=12),
        ),
        migrations.AlterField(
            model_name='logusuario',
            name='acao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('alteracao', 'Alteração')], default='criacao', max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('Feminino', 'feminino'), ('Masculino', 'masculino')], default='Feminino', max_length=9),
        ),
    ]
